In [5]:
%pip install pandas

import pandas as pd

students = {
    "Name": ["Nazmul", "Rahim", "Karim"],
    "Marks": [85, 90, 75]
}

df = pd.DataFrame(students)

average = df["Marks"].mean()

print("Class Average:", average)

  Using cached pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
Using cached tzdata-2026.2-py2.py3-none-any.whl (349 kB)

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
 


[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


Class Average: 83.33333333333333


In [6]:
import pandas as pd

data = {
    "Math": [80, 90, 70],
    "English": [75, 85, 95]
}

df = pd.DataFrame(data)

print(df.mean())

Math       80.0
English    85.0
dtype: float64


In [11]:
import numpy as np

data = pd.DataFrame({
    "Name": ["Alice", "Bob", np.nan, "Charlie"],
    "Age": [25, 30, 35,np.nan],
    "Salary": [50000, 60000, 70000, 80000]
})

In [12]:
data

,Name,Age,Salary
0,Alice,25.0,50000
1,Bob,30.0,60000
2,NaN,35.0,70000
3,Charlie,NaN,80000


In [13]:
data_dropped = data.dropna()
data_dropped

,Name,Age,Salary
0,Alice,25.0,50000
1,Bob,30.0,60000


In [14]:
data_filled = data.fillna({
    "Name": "Unknown",
    "Age": data["Age"].mean(),
    "Salary": data["Salary"].mean()
})
data_filled


,Name,Age,Salary
0,Alice,25.0,50000
1,Bob,30.0,60000
2,Unknown,35.0,70000
3,Charlie,30.0,80000


In [15]:
data_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
data_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
reshaped_array = data_array.reshape(3, 3)
print(reshaped_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
test_array = np.array([[1, 2, 3], [4, 5, 6]])

In [27]:
test_array

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
reshaped_array = test_array.reshape(3, 2)
print(reshaped_array)

[[1 2]
 [3 4]
 [5 6]]
